let suggestions = [
    "Paracetaamol 650",
    "Laveta M",
    "Ecosprin 75 mg",
    "Dolo 650mg",
    "Evion 400mg",
    "Pan 40mg",
    "Pan D Strip of 15 capsules",
    "Pantosec 40mg Tablet",
    "Pantop D Capsule",
    "Pantocid D Capsule",
    "Doxybond Lb Capsule",
    "Doxt Sl 100mg Strip of 10 Capsules",
    "Doxinate Strip of 30 Tablets",
    "Microdox Lbx Capsule",
    "Metrogyl 400mg Strip of 15 Tablets",
    "Flagyl 400mg Tablet",
    "Soframax Cream 15gm",
    "Zedott 10mg Capsule",
    "Zedocef Cv 200mg Strip of 10 Tablets",
    "Sedflox Oz Tablets",
    "Sedmont Lc Tablet",
    "Seder Om Tablet 15'5",
    "Tenoric 25mg Tablet",
    "Tel Revelol 40/25mg Table",
    "Levocetrizen 5mg Strip of 10 Tablets",
    "Letroz 2.5mg Tablet",
];